name: Build Windows Package

on: [workflow_dispatch, push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install Dependencies
      run: |
        choco install visualstudio2022buildtools --params "'/InstallAdditionalWorkloads netfx-4.8-devpack,Microsoft.VisualStudio.Workload.VCTools'"
        choco install visualstudio2022-workload-vctools
        choco install windows-sdk-10.1
    
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '8'
        
    - name: Set JAVA_PATH and JNI Paths
      run: |
        echo "JAVA_HOME=$(dirname $(dirname $(which java)))" >> $GITHUB_ENV
        echo "JNI_INCLUDE_PATH=$JAVA_HOME/include" >> $GITHUB_ENV
        echo "JNI_INCLUDE_PATH2=$JAVA_HOME/include/win32" >> $GITHUB_ENV
        echo "JNI_INCLUDE_DIRS=$JAVA_HOME/include;$JAVA_HOME/include/win32" >> $GITHUB_ENV

        
    - uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init
    
    - name: Build Package
      run: . ./buildjar.ps1 ; Host-Jar
      
    - uses: actions/upload-artifact@v2
      with:
        path: dist

