name: Build Windows Package

on: [workflow_dispatch, push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Setup MSBuild and Visual Studio 2022
      uses: microsoft/setup-msbuild@v2
        
    - uses: GuillaumeFalourd/setup-windows10-sdk-action@v2
      with:
        sdk-version: 22621

    - name: Get Windows SDK Installation Path
      run: gci "C:\Program Files (x86)\Windows Kits\" -Filter "WS2_32.Lib" -Recurse
      shell: powershell
     
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '8'
        
    - name: Set JAVA_PATH and JNI Paths
      run: |
        echo "JAVA_HOME=$(dirname $(dirname $(which java)))" >> $GITHUB_ENV
        echo "JNI_INCLUDE_PATH=$JAVA_HOME/include" >> $GITHUB_ENV
        echo "JNI_INCLUDE_PATH2=$JAVA_HOME/include/win32" >> $GITHUB_ENV
        echo "JNI_INCLUDE_DIRS=$JAVA_HOME/include;$JAVA_HOME/include/win32" >> $GITHUB_ENV

        
    - uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init
    
    - name: Build Package
      run: . ./buildjar.ps1
      
    - uses: actions/upload-artifact@v2
      with:
        path: dist

