name: Build Windows Package

on: [workflow_dispatch, push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          curl
          git
          tree
          cmake
          gcc
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        
    - shell: msys2 {0}
      run: | 
        cmd.exe
        jar -version
        exit
        

    - uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init
    
    - name: Build Package
      shell: msys2 {0}
      run: ./build.sh host-jar

    - uses: actions/upload-artifact@v2
      with:
        path: dist

