name: Build Windows Package

on: [workflow_dispatch, push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          curl
          git
          tree
          cmake
          gcc
    
    - name: Setup Java 17-open
      id: sdkman
      uses: sdkman/sdkman-action@b1f9b696c79148b66d3d3a06f7ea801820318d0f
      with:
        candidate: java
        version: 17-open
    - uses: actions/setup-java@v3
      id: setup-java
      with:
        distribution: 'jdkfile'
        java-version: 17
        jdkFile: ${{ steps.sdkman.outputs.file }}
        
    - shell: msys2 {0}
      run: | 
        cmd.exe
        jar -version
        exit
        

    - uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init
    
    - name: Build Package
      shell: msys2 {0}
      run: ./build.sh host-jar

    - uses: actions/upload-artifact@v2
      with:
        path: dist

