name: Build Windows Package

on: [workflow_dispatch, push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          curl
          git
          tree

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
    
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '8'
        
    - name: Set JAVA_PATH
      run: echo "JAVA_HOME=$(dirname $(dirname $(which java)))" >> $GITHUB_ENV
        
    - uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init
    
    - name: Build Package
      shell: msys2 {0}
      run: ./build.sh host-jar

    - uses: actions/upload-artifact@v2
      with:
        path: dist

