name: Build Windows Package

on: [workflow_dispatch, push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Setup MSBuild and Visual Studio 2022
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '2022'

    - name: Install Windows SDK
      uses: mscorlibdev/windows-sdk-installer@v1.4.0
      with:
        sdk-version: '10.0.22621.0'
    
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '8'
        
    - name: Set JAVA_PATH and JNI Paths
      run: |
        echo "JAVA_HOME=$(dirname $(dirname $(which java)))" >> $GITHUB_ENV
        echo "JNI_INCLUDE_PATH=$JAVA_HOME/include" >> $GITHUB_ENV
        echo "JNI_INCLUDE_PATH2=$JAVA_HOME/include/win32" >> $GITHUB_ENV
        echo "JNI_INCLUDE_DIRS=$JAVA_HOME/include;$JAVA_HOME/include/win32" >> $GITHUB_ENV

        
    - uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init
    
    - name: Build Package
      run: . ./buildjar.ps1
      
    - uses: actions/upload-artifact@v2
      with:
        path: dist

