name: Build Windows Package

on: [workflow_dispatch]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          curl
          git
    
    - name: Setup Java 8.0.362-zulu
      id: sdkman
      uses: sdkman/sdkman-action@b1f9b696c79148b66d3d3a06f7ea801820318d0f
      with:
        candidate: java
        version: 8.0.362-zulu
    - uses: actions/setup-java@v3
      id: setup-java
      with:
        distribution: 'jdkfile'
        java-version: 8
        jdkFile: ${{ steps.sdkman.outputs.file }}
    - run: java -version

    - uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init
    
    - name: Build Package
      shell: msys2 {0}
      run: ./build.sh host-jar

    - uses: actions/upload-artifact@v2
      with:
        path: dist

